### ISSUE TITLE
more flexible configuration of .env file, currently hardcoded

### ISSUE THREAD

**Issue by lukaszbudnik** [lukaszbudnik/auditor#3]
More flexible configuration of .env file, currently hardcoded.

Add go flag, if absent default to .env

**Comment by ilmanzo** [comment]
how about using [namsral/flag](https://github.com/namsral/flag) ?

**Comment by lukaszbudnik** [comment]
Done. Default configuration file is '.env' and now can be overridden by the `-configFile` flag.
